version: "3"

services:
  ### Schul-Cloud Server
  ###
  server-mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - data-server-mongodb:/data/db
    restart: unless-stopped

  server:
    build:
      context: ../schulcloud-server
      dockerfile: Dockerfile
    depends_on:
      - server-mongodb
      - redis
    environment:
      # ENV
      - NODE_ENV=production
      - HOST=http://localhost:3030
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud
      # SMTP
      - FORCE_SEND_EMAIL=true
      # Notifications service
      - NOTIFICATION_PLATFORM=testplatform
      - NOTIFICATION_URI=http://notification-service:3031
      # Storage
      - AWS_ENDPOINT_URL=https://dev-storage.schul-cloud.org:9001
      #- AWS_ENDPOINT_URL=http://localhost:9000
      ## keys for local s3 storage
      # - AWS_ACCESS_KEY=
      # - AWS_SECRET_ACCESS_KEY=
      # URIs and Port
      - MONGO_URI=mongodb://server-mongodb:27017/schulcloud
      - DB_URL=mongodb://server-mongodb:27017/schulcloud
      - REDIS_URI=redis://redis:6379
      - PORT=3030
      - CONTENT_URI=https://content.schul-cloud.org
      # RocketChat
      - ROCKET_CHAT_URI=https://chat.schulcloud.local
      # - ROCKET_CHAT_ADMIN_TOKEN=
      # - ROCKET_CHAT_ADMIN_TOKEN=
      # - ROCKET_CHAT_ADMIN_ID=
      # AUTH Secret
      # - AUTHENTICATION=
      - IGNORE_DISCOVERABILITY=true
      # BRUTE FORCE PROTECTION
      - LOGIN_BLOCK_TIME=3
      # FEATURE TOGGLES
      - LERNSTORE_MODE=LEGACY
    ports:
      - "3030:3030"
      - "5959:5959"
    restart: unless-stopped
    command: npm run start
  ###

  ### Schul-Cloud Client
  ###
  client:
    build:
      context: ../schulcloud-client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      # ENV
      - NODE_ENV=development
      - DOCKER=true
      - CALENDAR_SERVICE_ENABLED=true
      #- TZ=Europe/Berlin
      # Theme and Titles
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud
      - SC_PRODUCTNAME=Hauptschule
      - SC_FEDERALSTATE=mainstate
      # Google
      #- GOOGLE_ANALYTICS_TRACKING_ID="UA-155982548-1"
      # URIs
      - HOST=http://localhost:3100
      - BACKEND_URL=http://server:3030
      - PUBLIC_BACKEND_URL=https://localhost:3030
        # - LIBRE_OFFICE_CLIENT_URL=http://localhost:9980
        # - ROCKET_CHAT_URI=https://chat.schulcloud.local
      # FEATURE TOGGLES
      - FEATURE_TEAMS_ENABLED=true
      - FEATURE_EXTENSIONS_ENABLED=true
      - LERNSTORE_MODE=LEGACY
      # - ROCKETCHAT_SERVICE_ENABLED=true
      # - EDTR_SOURCE=https://cdn.jsdelivr.net/gh/schul-cloud/edtrio@e9d3bb9d66092bafa07846269c8fc6f9d5fb0559/dist/index.js
      # BRUTE FORCE PROTECTION
      - LOGIN_BLOCK_TIME=3
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: npm run start

  nuxtclient:
    build:
      context: ../nuxt-client
      dockerfile: deploy/Dockerfile.client
    depends_on:
      - server
      - client
    environment:
      # ENV
      - NODE_ENV=production
      - TZ=Europe/Berlin
      - LEGACY_CLIENT_URL=http://client:3100
      - HOST=0.0.0.0
      - API_URL=http://server:3030
      # FEATURE TOGGLES
      - FEATURE_TEAMS_ENABLED=true
      - LERNSTORE_MODE=LEGACY
      # Theme and Titles
      - SC_THEME=default
    ports:
      - "4000:4000"
    restart: unless-stopped

  # Selenium Server
  selenium-hub:
    image: selenium/hub:3.141.59-titanium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
#   firefox:
#     image: selenium/node-firefox:3.141.59-titanium
#     volumes:
#       - /dev/shm:/dev/shm
#     depends_on:
#       - selenium-hub
#     environment:
#       - HUB_HOST=selenium-hub
#       - HUB_PORT=4444

  # Notification Service

  notification-service:
    build:
      context: ../node-notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - 3031:3031
    environment:
      - MONGO_HOST=server-mongodb
      - REDIS_HOST=redis
    volumes:
      - ../integration-tests/ci/config/notification-service/testplatform.config.json:/usr/src/app/platforms/testplatform/config.json
      - ./logs:/usr/src/app/logs
    depends_on:
      - server-mongodb
      - redis
      - mail
    command: sh -c "npm run build & npm run start"


  redis:
    image: redis:5.0.3

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  data-server-mongodb:
